version: '3.9'
services:
    express-typeorm-example:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        expose:
            - '3000'
        ports:
            - '80:3000'
        environment:
            PORT: '3000'
            DB_HOST: db
            DB_PORT: '5432'
        depends_on:
            - db
        links:
            - db
        command: node dist/server.js
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 'postgres'
